
name: 디스코드 알림봇

on:
  schedule: 
    - cron: "*/1 * * * *"
jobs:
  message:
    runs-on: ubuntu-latest
    steps:
    - name: Discord Webhook action
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
        content: "10분 간격 알림 테스트 @here"
